### PR TITLE
Allow customizing the primary key of the model

### PR DESCRIPTION
**Pull request by chessbr**
Allow customizing the primary key field on the default Migrator tool

### CODE REVIEW

**Comment by tcitry** [comment]
Looks awesome, and taged with `1.2.1`

**Comment by chessbr** [comment]
@tcitry can you also release that to v2 beta as we are using that? Thank you! 😃

**Comment by tcitry** [comment]
@chessbr  hi, v2 beta is published with v 1.2.0，so your pr in v1.2.1 is having v2-beta !

**Comment by chessbr** [comment]
@tcitry thank you so much! I probably forgot to also update the management command to have that param.

**Pull request merged**
